name: Biome check

on:
  pull_request:
    branches: ["*"]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Bun & Nx Setup
        uses: ./.github/actions/setup-bun-nx

      - name: Run Nx affected check
        run: npx nx affected -t check --base=origin/master --head=HEAD
